<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Trip Report - {{ $trip->name }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; margin: 20px; }
        h1 { color: #333; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .summary { margin-bottom: 20px; }
    </style>
</head>
<body>
    <h1>Trip Report: {{ $trip->name }}</h1>
    <div class="summary">
        <div><strong>Dates:</strong> {{ $trip->start_date->format('Y-m-d') }} to {{ $trip->end_date->format('Y-m-d') }}</div>
        <div><strong>Total Budget:</strong> ${{ number_format($trip->total_budget, 2) }}</div>
        <div><strong>Total Spent:</strong> ${{ number_format($totalSpent, 2) }}</div>
        <div><strong>Remaining:</strong> ${{ number_format($remainingBudget, 2) }}</div>
    </div>

    <h3>Expenses</h3>
    <table>
        <thead>
            <tr><th>Date</th><th>Category</th><th>Amount</th><th>Description</th></tr>
        </thead>
        <tbody>
            @foreach($budgets as $expense)
            <tr>
                <td>{{ $expense->expense_date->format('Y-m-d') }}</td>
                <td>{{ ucfirst($expense->category) }}</td>
                <td>${{ number_format($expense->amount, 2) }}</td>
                <td>{{ $expense->description ?? '-' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <h3>Destinations</h3>
    <ul>
        @foreach($destinations as $dest)
            <li>{{ $dest->city }}, {{ $dest->country }} ({{ $dest->arrival_date->format('Y-m-d') }} - {{ $dest->departure_date->format('Y-m-d') }})</li>
        @endforeach
    </ul>

    <p style="margin-top: 40px;"><small>Generated by SmartTrip AI on {{ now()->format('Y-m-d H:i') }}</small></p>
</body>
</html>